# Generated by Django 4.2.8 on 2025-11-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Price in cents (e.g. 1999 = $19.99)')),
                ('file', models.FileField(blank=True, null=True, upload_to='products/files/')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Optional Stripe Price ID for hosted checkout', max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=230, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='blogposts', to='content.product')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogposts', to='content.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
