# Generated by Django 4.2.8 on 2025-11-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_product_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Optional Stripe Product ID', max_length=200, null=True),
        ),
    ]
