# Generated by Django 4.2.8 on 2025-11-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Optional external affiliate or vendor URL', max_length=1000, null=True),
        ),
    ]
