# Generated by Django 4.2.8 on 2025-11-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_product_affiliate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_clicks',
            field=models.PositiveIntegerField(default=0, help_text='Count of outbound affiliate clicks'),
        ),
    ]
