# Generated by Django 4.2.8 on 2025-11-22 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Friendly label shown in downloads', max_length=200, null=True)),
                ('file', models.FileField(upload_to='contact/')),
                ('file_type', models.CharField(choices=[('cv', 'CV'), ('cert', 'Certification'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
