# Generated by Django 4.2.8 on 2025-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_service_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF file of the certification', upload_to='resources/certifications/')),
                ('title', models.CharField(help_text='Certification name (e.g., "AWS Certified Solutions Architect")', max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='Issuing organization', max_length=200)),
                ('issue_date', models.DateField(blank=True, help_text='Date when certification was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Only published certifications will be displayed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-issue_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF file of your CV', upload_to='resources/cv/')),
                ('title', models.CharField(default='CV', help_text='Display title (e.g., "My CV" or "Resume")', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active CV will be displayed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-is_active', '-uploaded_at'],
            },
        ),
    ]
