# Generated by Django 4.2.8 on 2025-11-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_certification_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=200)),
                ('title', models.CharField(help_text='Your professional title (e.g., "Full Stack Developer")', max_length=200)),
                ('profile_image', models.ImageField(blank=True, help_text='Your profile picture', null=True, upload_to='about/')),
                ('bio', models.TextField(help_text='Short bio/introduction')),
                ('long_description', models.TextField(blank=True, help_text='Detailed about section')),
                ('location', models.CharField(blank=True, help_text='Your location (e.g., "New York, NY")', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Personal website URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('resume_url', models.URLField(blank=True, help_text='Link to resume/CV')),
                ('is_published', models.BooleanField(default=True, help_text='Publish the about page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
                'ordering': ['-updated_at'],
            },
        ),
    ]
