# Generated by Django 4.2.8 on 2025-11-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default='Hi — I design & operate cloud-first apps', help_text='Greeting text (e.g., "Hi — I design & operate cloud-first apps")', max_length=200)),
                ('typing_prefix', models.CharField(default='I am', help_text='Text before typing animation (e.g., "I am")', max_length=50)),
                ('typing_strings', models.TextField(default='Cloud Engineer\nWeb Developer\nGraphics & Logo Designer', help_text='Comma or newline-separated list of strings for typing animation')),
                ('main_title', models.CharField(default='Building Cloud-Powered Digital Experiences That Scale', help_text='Main hero title', max_length=300)),
                ('button1_text', models.CharField(default='Hire me', help_text='First button text', max_length=100)),
                ('button1_link', models.CharField(default='#contact', help_text='First button link (e.g., "#contact" or "/contact")', max_length=200)),
                ('button2_text', models.CharField(default='View portfolio', help_text='Second button text', max_length=100)),
                ('button2_link', models.CharField(default='/portfolio', help_text='Second button link', max_length=200)),
                ('background_video', models.FileField(blank=True, help_text='Background video file (MP4)', null=True, upload_to='hero/')),
                ('background_image', models.ImageField(blank=True, help_text='Background image (fallback if no video)', null=True, upload_to='hero/')),
                ('scroll_text', models.CharField(blank=True, default='Scroll to explore', help_text='Text at bottom of hero', max_length=200)),
                ('is_published', models.BooleanField(default=True, help_text='Publish the hero section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'ordering': ['-updated_at'],
            },
        ),
    ]
