# Generated by Django 4.2.8 on 2025-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL to view the project on GitHub', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='live_url',
            field=models.URLField(blank=True, help_text='URL to view the project live', max_length=500),
        ),
    ]
