# Generated by Django 4.2.8 on 2025-11-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_portfolio_github_url_portfolio_live_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn_mobile_money', models.CharField(blank=True, help_text='MTN Mobile Money number', max_length=20)),
                ('orange_money', models.CharField(blank=True, help_text='Orange Money number', max_length=20)),
                ('card_number', models.CharField(blank=True, help_text='Card number for donations', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation Information',
                'verbose_name_plural': 'Donation Information',
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(help_text='Uploaded gift card image', upload_to='donations/gift_cards/')),
                ('donor_name', models.CharField(blank=True, help_text='Name of the donor (optional)', max_length=200)),
                ('donor_email', models.EmailField(blank=True, help_text='Email of the donor (optional)', max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Gift card amount (if known)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('is_processed', models.BooleanField(default=False, help_text='Mark as processed when redeemed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=200)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=200)),
                ('account_number', models.CharField(help_text='Account number', max_length=50)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code (if applicable)', max_length=20)),
                ('branch', models.CharField(blank=True, help_text='Branch name/location', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='content.donationinfo')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
                'ordering': ['order', 'bank_name'],
            },
        ),
    ]
