# Generated by Django 4.2.8 on 2026-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_donationinfo_giftcard_bankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video URL for product demo', max_length=1000, null=True),
        ),
    ]
