# Generated by Django 4.2.8 on 2026-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_product_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL to view the project on GitHub', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='live_url',
            field=models.URLField(blank=True, help_text='URL to view the project live', max_length=500),
        ),
    ]
