# Generated by Django 4.2.8 on 2026-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_product_github_url_product_live_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, help_text='Product cover/thumbnail image', null=True, upload_to='products/covers/'),
        ),
    ]
