# Generated by Django 4.2.8 on 2026-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_old_fields_add_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects-for-sale/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=10, null=True)),
                ('whatsapp_url', models.URLField(blank=True, help_text='WhatsApp chat URL', max_length=500)),
                ('live_url', models.URLField(blank=True, help_text='Live project URL or YouTube video', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL to view the project on GitHub', max_length=500, null=True),
        ),
    ]
